In [2]:
import pandas as pd
import numpy as np

In [20]:
data_for_measure_df = pd.read_csv(r"C:\Users\memel\PycharmProjects\Text_collision_auditor1\rag\measurements\data_test_for_measure(YGPT, full).csv")

In [ ]:
data_for_measure_df.head(40)

In [14]:
data_for_measure_df.iloc[0]['text']

"['OBJECTIVES To carry out a further survey of archived appendix samples to understand better the differences between existing estimates of the prevalence of subclinical infection with prions after the bovine spongiform encephalopathy epizootic and to see whether a broader birth cohort was affected, and to understand better the implications for the management of blood and blood products and for the handling of surgical instruments.   \\n', 'DESIGN Irreversibly unlinked and anonymised large scale survey of archived appendix samples.   \\n', 'SETTING Archived appendix samples from the pathology departments of 41 UK hospitals participating in the earlier survey, and additional hospitals in regions with lower levels of participation in that survey.   ', 'SAMPLE 32,441 archived appendix samples fixed in formalin and embedded in paraffin and tested for the presence of abnormal prion protein (PrP).   \\n', 'RESULTS Of the 32,441 appendix samples 16 were positive for abnormal PrP, indicating an overall prevalence of 493 per million population (95% confidence interval 282 to 801 per million).', 'The prevalence in those born in 1941-60 (733 per million, 269 to 1596 per million) did not differ significantly from those born between 1961 and 1985 (412 per million, 198 to 758 per million) and was similar in both sexes and across the three broad geographical areas sampled.', 'Genetic testing of the positive specimens for the genotype at PRNP codon 129 revealed a high proportion that were valine homozygous compared with the frequency in the normal population, and in stark contrast with confirmed clinical cases of vCJD, all of which were methionine homozygous at PRNP codon 129.   \\n', 'CONCLUSIONS This study corroborates previous studies and suggests a high prevalence of infection with abnormal PrP, indicating vCJD carrier status in the population compared with the 177 vCJD cases to date.', 'These findings have important implications for the management of blood and blood products and for the handling of surgical instruments.', '1 in 5 million in UK have abnormal PrP positivity.']"

In [41]:
data_for_measure_df.to_csv(r"C:\Users\memel\PycharmProjects\Text_collision_auditor\rag\measurements\data_test_for_measure.csv",
                      index=False)

In [47]:
data_for_measure_df = pd.read_csv(r"C:\Users\memel\PycharmProjects\Text_collision_auditor\rag\measurements\data_train_for_measure.csv")

In [ ]:
data_for_measure_df.head(22)

In [32]:
data_for_measure_df.at[4, 'text']

"['In systemic lupus erythematosus (SLE), self-reactive antibodies can target the kidney (lupus nephritis), leading to functional failure and possible mortality.', 'We report that activation of basophils by autoreactive IgE causes their homing to lymph nodes, promoting T helper type 2 (T(H)2) cell differentiation and enhancing the production of self-reactive antibodies that cause lupus-like nephritis in mice lacking the Src family protein tyrosine kinase Lyn (Lyn(-/-) mice).', 'Individuals with SLE also have elevated serum IgE, self-reactive IgEs and activated basophils that express CD62 ligand (CD62L) and the major histocompatibility complex (MHC) class II molecule human leukocyte antigen-DR (HLA-DR), parameters that are associated with increased disease activity and active lupus nephritis.', 'Basophils were also present in the lymph nodes and spleen of subjects with SLE.', 'Thus, in Lyn(-/-) mice, basophils and IgE autoantibodies amplify autoantibody production that leads to lupus nephritis, and in individuals with SLE IgE autoantibodies and activated basophils are factors associated with disease activity and nephritis.', 'A T helper 2 cell (Th2) environment impedes disease development in patients with systemic lupus erythematosus (SLE).']"

In [23]:
data_for_measure_df.to_csv(r"C:\Users\memel\PycharmProjects\Text_collision_auditor1\rag\measurements\data_test_for_measure(YGPTPRO, with costyly).csv",
                      index=False)

In [5]:
df = pd.read_csv(r"test_wiki(YGPT).csv")

In [6]:
df.head(10)

,corpus,contradict,neutral,pred_contr,pred_neutr,col_contr,col_neutr
0,"I Loves You, Porgy\r\n\r\n""I Loves You, Porgy""...",Bill Evans's piano trio version recorded at th...,Bill Evans's piano trio version recorded at th...,1.0,1.0,"[""bill evans's piano trio version recorded at ...",[]
1,Great Valley Nature Center\r\n\r\nThe Great Va...,"As of Winter 2019, the property is currently o...","As of Spring 2019, the property is currently o...",0.0,1.0,[],[]
2,Louis Anderson\r\n\r\nLouis Manu Anderson (bor...,He played in the 2012 Challenge Cup Final vict...,He played in the 2010 Challenge Cup Final vict...,1.0,1.0,['Anderson played for Warrington in their 2010...,[]
3,Epiphany (novel)\r\n\r\nEpiphany is a 1997 mys...,Fellow student Hal Jamieson finds himself tryi...,Fellow student Hal Jamieson finds himself tryi...,1.0,1.0,['paul dunsany is a kind hearted musician'],[]

In [26]:
df.at[1, 'corpus']

'Great Valley Nature Center\n\nThe Great Valley Nature Center was an American organization dedicated to raising public awareness on environmental issues through educational exhibits, demonstrations, and workshops. The Great Valley Nature Center was located in Malvern, Pennsylvania. It consistes of fields, streams, ponds, woods, and diverse habitats. Also featured was Birds of Prey Center. All birds of prey are no longer presenta replica Native American Lenape village, a Pennsylvania wildflower garden, a maple sugar house, and a hands-on exhibit area were also present.\n\nHistory \nSince its November 1974 incorporation, Great Valley Nature Center (formerly the Nature Center of Charlestown) has provided the Greater Philadelphia region, including Chester County, with environmental education opportunities. Arnold Bartschi contributed the land and start-up costs to establish the nature center.\n\nAs of 2017, the corporation has been dissolved. \nAs of Spring 2019, the property is currently owned by a bank that wishes to foreclose upon it and sell it to a private party.'

In [10]:
original_df = pd.read_csv(r"C:\Users\memel\PycharmProjects\Text_collision_auditor1\rag\measurements\test_wiki.csv")

In [18]:
original_df.shape

(300, 3)

In [21]:
results_without_new_prompt = pd.read_csv(r"test_wiki(YGPT).csv")

In [22]:
results_without_new_prompt.head()

,corpus,contradict,neutral,pred_contr,pred_neutr
0,"I Loves You, Porgy\r\n\r\n""I Loves You, Porgy""...",Bill Evans's piano trio version recorded at th...,Bill Evans's piano trio version recorded at th...,1.0,1.0
1,Great Valley Nature Center\r\n\r\nThe Great Va...,"As of Winter 2019, the property is currently o...","As of Spring 2019, the property is currently o...",0.0,1.0
2,Louis Anderson\r\n\r\nLouis Manu Anderson (bor...,He played in the 2012 Challenge Cup Final vict...,He played in the 2010 Challenge Cup Final vict...,1.0,1.0
3,Epiphany (novel)\r\n\r\nEpiphany is a 1997 mys...,Fellow student Hal Jamieson finds himself tryi...,Fellow student Hal Jamieson finds himself tryi...,1.0,1.0
4,Dictionary of Serbo-Croatian Literary and Vern...,"Since the break-up of Yugoslavia, the publicat...","Since the break-up of Yugoslavia, the publicat...",1.0,1.0

In [24]:
results_with_new_prompt = pd.read_csv(r"test_wiki(YGPT, new prompt with NO).csv")

In [25]:
results_with_new_prompt.head()

,corpus,contradict,neutral,pred_contr,pred_neutr
0,"I Loves You, Porgy\r\n\r\n""I Loves You, Porgy""...",Bill Evans's piano trio version recorded at th...,Bill Evans's piano trio version recorded at th...,1.0,1.0
1,Great Valley Nature Center\r\n\r\nThe Great Va...,"As of Winter 2019, the property is currently o...","As of Spring 2019, the property is currently o...",0.0,1.0
2,Louis Anderson\r\n\r\nLouis Manu Anderson (bor...,He played in the 2012 Challenge Cup Final vict...,He played in the 2010 Challenge Cup Final vict...,1.0,1.0