In [1]:
import pandas as pd
import numpy as np

In [20]:
data_for_measure_df = pd.read_csv(r"C:\Users\memel\PycharmProjects\Text_collision_auditor1\rag\measurements\data_test_for_measure(YGPT, full).csv")

In [21]:
data_for_measure_df.head(40)

,text_id,text,len_text,true_pair,pred_pair
0,0,['Genome-wide association studies (GWAS) have ...,9,[],"[(8, 0), (8, 1)]"
1,1,['OBJECTIVES To carry out a further survey of ...,10,[],"[(9, 4)]"
2,2,['BACKGROUND The heritable haemoglobinopathy a...,15,"[(14, 1), (14, 9), (14, 10)]","[(14, 2), (14, 11), (14, 12)]"
3,3,['OBJECTIVES To carry out a further survey of ...,10,"[(9, 4)]",[]
4,4,['Adenosine deaminases acting on RNA (ADARs) a...,6,[],[]
5,5,['Expression of the intermediate filament prot...,5,[],[]
6,6,['Application of stem cell biology to breast c...,7,"[(6, 4)]","[(6, 4)]"
7,7,['Application of stem cell biology to breast c...,7,[],[]
8,8,['Fibrosis is a pathological result of a dysfu...,9,"[(8, 5), (8, 6), (8, 7)]","[(8, 7)]"
9,9,"[""Efforts to develop drugs for Alzheimer's dis...",7,[],[]
10,10,"[""Efforts to develop drugs for Alzheimer's dis...",7,"[(6, 1)]","[(6, 1)]"
11,11,['Gliomas arising in the brainstem and thalamu...,9,[],[]
12,12,['Improved sequencing technologies offer unpre...,10,[],[]
13,13,['Stem cells are proposed to segregate chromos...,9,[],"[(8, 0), (8, 1)]"
14,14,['Angiotensin converting enzyme (ACE) inhibito...,11,[],[]
15,15,"[""CONTEXT Bioterrorist attacks involving lette...",9,"[(8, 6)]",[]
16,16,['Antibiotics can have significant and long-la...,6,[],[]
17,17,['BACKGROUND Human immunodeficiency virus (HIV...,14,[],[]
18,18,['PLoS Biology publishes today a research arti...,43,"[(42, 2), (42, 10), (42, 11), (42, 40)]","[(42, 5)]"
19,19,['PLoS Biology publishes today a research arti...,43,[],[]
20,20,['Podosomes (also termed invadopodia in cancer...,9,[],[]
21,21,['OBJECTIVE To assess whether population scree...,14,[],"[(13, 10)]"
22,22,['UNLABELLED Congruent audiovisual speech enha...,16,[],[]
23,23,['CONTEXT Antibody-based induction therapy plu...,15,"[(14, 12)]",[]
24,24,['CONTEXT Antibody-based induction therapy plu...,15,[],[]
25,25,['CONTEXT Antibody-based induction therapy plu...,15,[],[]
26,26,"['Chaperone-mediated autophagy (CMA), a select...",7,[],"[(6, 5)]"
27,27,['IMPORTANCE Bariatric surgery is associated w...,14,[],[]
28,28,"['In systemic lupus erythematosus (SLE), self-...",6,"[(5, 1), (5, 2), (5, 4)]","[(5, 1), (5, 2), (5, 4)]"
29,29,"['BACKGROUND Birth size, perhaps a proxy for p...",13,[],[]
30,30,"['Breast cancer may originate in utero.', 'We ...",10,[],[]
31,31,['BACKGROUND Emerging evidence suggests an ass...,12,[],[]
32,32,"['INTRODUCTION Various perinatal factors, incl...",11,[],[]
33,33,['Genetic mutations in TAR DNA-binding protein...,8,"[(7, 5)]",[]
34,34,['Despite accumulating evidence suggesting loc...,7,"[(6, 3)]","[(6, 5)]"
35,35,['BACKGROUND Information is scarce about the c...,9,"[(8, 2), (8, 6)]","[(8, 0), (8, 3), (8, 4)]"
36,36,['Background Checkpoint kinase 2 (CHEK2) avert...,11,[],"[(10, 1), (10, 3)]"
37,37,"['In mammals, caloric restriction consistently...",10,"[(9, 1), (9, 3), (9, 4), (9, 7), (9, 8)]",[]
38,38,['Allergic asthma is a T helper type 2 (T(H)2)...,8,"[(7, 4)]",[]
39,39,['Allergic asthma is a T helper type 2 (T(H)2)...,8,[],[]

In [14]:
data_for_measure_df.iloc[0]['text']

"['OBJECTIVES To carry out a further survey of archived appendix samples to understand better the differences between existing estimates of the prevalence of subclinical infection with prions after the bovine spongiform encephalopathy epizootic and to see whether a broader birth cohort was affected, and to understand better the implications for the management of blood and blood products and for the handling of surgical instruments.   \\n', 'DESIGN Irreversibly unlinked and anonymised large scale survey of archived appendix samples.   \\n', 'SETTING Archived appendix samples from the pathology departments of 41 UK hospitals participating in the earlier survey, and additional hospitals in regions with lower levels of participation in that survey.   ', 'SAMPLE 32,441 archived appendix samples fixed in formalin and embedded in paraffin and tested for the presence of abnormal prion protein (PrP).   \\n', 'RESULTS Of the 32,441 appendix samples 16 were positive for abnormal PrP, indicating an overall prevalence of 493 per million population (95% confidence interval 282 to 801 per million).', 'The prevalence in those born in 1941-60 (733 per million, 269 to 1596 per million) did not differ significantly from those born between 1961 and 1985 (412 per million, 198 to 758 per million) and was similar in both sexes and across the three broad geographical areas sampled.', 'Genetic testing of the positive specimens for the genotype at PRNP codon 129 revealed a high proportion that were valine homozygous compared with the frequency in the normal population, and in stark contrast with confirmed clinical cases of vCJD, all of which were methionine homozygous at PRNP codon 129.   \\n', 'CONCLUSIONS This study corroborates previous studies and suggests a high prevalence of infection with abnormal PrP, indicating vCJD carrier status in the population compared with the 177 vCJD cases to date.', 'These findings have important implications for the management of blood and blood products and for the handling of surgical instruments.', '1 in 5 million in UK have abnormal PrP positivity.']"

In [41]:
data_for_measure_df.to_csv(r"C:\Users\memel\PycharmProjects\Text_collision_auditor\rag\measurements\data_test_for_measure.csv",
                      index=False)

In [47]:
data_for_measure_df = pd.read_csv(r"C:\Users\memel\PycharmProjects\Text_collision_auditor\rag\measurements\data_train_for_measure.csv")

In [48]:
data_for_measure_df.head(22)

,text_id,text,len_text,true_pair,pred_pair
0,0,['OBJECTIVES To carry out a further survey of ...,10,"[(9, 4)]","[(9, 4), (9, 7)]"
1,1,['ContextChronic hepatitis C is the leading ca...,17,[],"[(16, 10)]"
2,2,['CONTEXT High plasma homocysteine levels are ...,15,[],[]
3,3,['CONTEXT Little is known about the extent or ...,13,[],[]
4,4,"['In systemic lupus erythematosus (SLE), self-...",6,"[(5, 1), (5, 2), (5, 4)]","[(5, 1), (5, 2), (5, 4)]"
5,5,['CONTEXT The growth inhibitory effect of tamo...,15,[],[]
6,6,['BACKGROUND Adoption of new and underutilized...,11,"[(10, 8)]","[(10, 4)]"
7,7,['BACKGROUND Lowering serum homocysteine level...,11,[],[]
8,8,['Importance Despite lack of evidence of their...,14,[],[]
9,9,['Importance Despite lack of evidence of their...,14,"[(13, 7), (13, 8), (13, 9), (13, 10), (13, 11)]","[(13, 7), (13, 8), (13, 9), (13, 11), (13, 12)]"
10,10,['BACKGROUND The heritable haemoglobinopathy a...,15,[],[]
11,11,['Background Macrosomia is associated with co...,5,[],[]
12,12,['Hypospadias is a common congenital malformat...,6,[],[]
13,13,['Clustered regularly interspaced short palind...,9,[],[]
14,14,['Application of stem cell biology to breast c...,7,[],[]
15,15,['Fibrosis is a pathological result of a dysfu...,9,[],[]
16,16,"[""Efforts to develop drugs for Alzheimer's dis...",7,"[(6, 1)]","[(6, 1)]"
17,17,['BACKGROUND Many mathematical models have inv...,15,"[(14, 5), (14, 9), (14, 11)]",[]
18,18,['BACKGROUND Many mathematical models have inv...,15,[],[]
19,19,['The phosphatidylinositol-3-kinase-like kinas...,9,[],[]
20,20,['The phosphatidylinositol-3-kinase-like kinas...,9,[],[]
21,21,['Gliomas arising in the brainstem and thalamu...,9,"[(8, 5), (8, 6)]",[]

In [32]:
data_for_measure_df.at[4, 'text']

"['In systemic lupus erythematosus (SLE), self-reactive antibodies can target the kidney (lupus nephritis), leading to functional failure and possible mortality.', 'We report that activation of basophils by autoreactive IgE causes their homing to lymph nodes, promoting T helper type 2 (T(H)2) cell differentiation and enhancing the production of self-reactive antibodies that cause lupus-like nephritis in mice lacking the Src family protein tyrosine kinase Lyn (Lyn(-/-) mice).', 'Individuals with SLE also have elevated serum IgE, self-reactive IgEs and activated basophils that express CD62 ligand (CD62L) and the major histocompatibility complex (MHC) class II molecule human leukocyte antigen-DR (HLA-DR), parameters that are associated with increased disease activity and active lupus nephritis.', 'Basophils were also present in the lymph nodes and spleen of subjects with SLE.', 'Thus, in Lyn(-/-) mice, basophils and IgE autoantibodies amplify autoantibody production that leads to lupus nephritis, and in individuals with SLE IgE autoantibodies and activated basophils are factors associated with disease activity and nephritis.', 'A T helper 2 cell (Th2) environment impedes disease development in patients with systemic lupus erythematosus (SLE).']"

In [23]:
data_for_measure_df.to_csv(r"C:\Users\memel\PycharmProjects\Text_collision_auditor1\rag\measurements\data_test_for_measure(YGPTPRO, with costyly).csv",
                      index=False)

In [45]:
df = pd.read_csv(r"test_wiki(YGPT).csv")

In [46]:
df.head(10)

,Unnamed: 0,corpus,contradict,neutral,pred_contr,pred_neutr,col_contr,col_neutr
0,0,"I Loves You, Porgy\n\n""I Loves You, Porgy"" is ...",Bill Evans's piano trio version recorded at th...,Bill Evans's piano trio version recorded at th...,0.0,1.0,0,[]
1,1,Great Valley Nature Center\n\nThe Great Valley...,"As of Winter 2019, the property is currently o...","As of Spring 2019, the property is currently o...",0.0,1.0,0,[]
2,2,Louis Anderson\n\nLouis Manu Anderson (born 27...,He played in the 2012 Challenge Cup Final vict...,He played in the 2010 Challenge Cup Final vict...,0.0,1.0,0,[]
3,3,Epiphany (novel)\n\nEpiphany is a 1997 mystery...,Fellow student Hal Jamieson finds himself tryi...,Fellow student Hal Jamieson finds himself tryi...,1.0,1.0,['Fellow student Hal Jamieson finds himself tr...,[]
4,4,Dictionary of Serbo-Croatian Literary and Vern...,"Since the break-up of Yugoslavia, the publicat...","Since the break-up of Yugoslavia, the publicat...",0.0,1.0,0,[]
5,5,"Yoho River\n\nThe Yoho River is a silty, swift...",It continues north for another to its confluen...,It continues south for another to its conflue...,0.0,1.0,0,[]
6,6,"Maquiladora\n\nA maquiladora ([makilaˈðoɾa]), ...","On the contrary, by the end of the conflicts, ...","On the contrary, by the end of the conflicts, ...",0.0,0.0,0,0
7,7,Daihatsu Luxio\n\nThe Daihatsu Luxio is a mini...,"The Luxio lacks airbags, but optional ABS was ...","The Luxio lacks airbags, but optional ABS was ...",1.0,1.0,['M trim was discontinued with the facelifted ...,[]
8,8,Laurie C. Battle\n\nLaurie Calvin Battle (May ...,He was not a candidate for renomination in 195...,He was not a candidate for renomination in 195...,0.0,1.0,0,[]
9,9,Parmiter's Bethnal Green Educational Fund\n\nP...,The Trustees therefore piloted a project in Ba...,The Trustees therefore piloted a project in Ba...,0.0,1.0,0,[]

In [26]:
df.at[1, 'corpus']

'Great Valley Nature Center\n\nThe Great Valley Nature Center was an American organization dedicated to raising public awareness on environmental issues through educational exhibits, demonstrations, and workshops. The Great Valley Nature Center was located in Malvern, Pennsylvania. It consistes of fields, streams, ponds, woods, and diverse habitats. Also featured was Birds of Prey Center. All birds of prey are no longer presenta replica Native American Lenape village, a Pennsylvania wildflower garden, a maple sugar house, and a hands-on exhibit area were also present.\n\nHistory \nSince its November 1974 incorporation, Great Valley Nature Center (formerly the Nature Center of Charlestown) has provided the Greater Philadelphia region, including Chester County, with environmental education opportunities. Arnold Bartschi contributed the land and start-up costs to establish the nature center.\n\nAs of 2017, the corporation has been dissolved. \nAs of Spring 2019, the property is currently owned by a bank that wishes to foreclose upon it and sell it to a private party.'